from esphome.const import (
    CONF_ID,
    CONF_MAC_ADDRESS,
    CONF_NAME,
    CONF_PASSWORD,
    CONF_UPDATE_INTERVAL,
)

DOMAIN = "paulmann_lights"

CONF_PAULMANN_LIGHTS_ID = "paulmann_lights_id"
CONF_CONNECTION_RETRIES = "connection_retries"

CONF_TIMER = "timer"
CONF_WORKING_MODE = "working_mode"
CONF_CONTROLLER_ENABLE = "controller_enable"

CONF_SYSTEM_ID = "system_id"
CONF_MODEL = "model"
CONF_SERIAL_NUMBER = "serial_number"
CONF_FIRMWARE_REVISION = "firmware_revision"
CONF_HARDWARE_REVISION = "hardware_revision"
CONF_SOFTWARE_REVISION = "software_revision"
CONF_MANUFACTURER = "manufacturer"
CONF_IEEE_CERTIFICATION = "ieee_certification"
CONF_PNP_ID = "pnp_id"

DEFAULT_PASSWORD = "1234"
DEFAULT_NAME = "Paulmann Light"
DEFAULT_CONNECTION_RETRIES = 5
DEFAULT_UPDATE_INTERVAL = "30s"

UUID_SERVICE_PAULMANN = 0xFFB0
UUID_SERVICE_DEVICE_INFO = 0x180A

UUID_SYSTEM_TIME = 0xFFB3
UUID_TIMER = 0xFFB4
UUID_NAME = 0xFFB5
UUID_COLOR = 0xFFB6
UUID_ONOFF = 0xFFB7
UUID_BRIGHTNESS = 0xFFB8
UUID_WORKING_MODE = 0xFFB9
UUID_PWD = 0xFFBA
UUID_CONTROLLER_ENABLE = 0xFFBB

UUID_INFO_SYSTEM_ID = 0x2A23
UUID_INFO_MODEL = 0x2A24
UUID_INFO_SERIAL_NUMBER = 0x2A25
UUID_INFO_FIRMWARE_REVISION = 0x2A26
UUID_INFO_HARDWARE_REVISION = 0x2A27
UUID_INFO_SOFTWARE_REVISION = 0x2A28
UUID_INFO_MANUFACTURER = 0x2A29
UUID_INFO_IEEE_CERT = 0x2A2A
UUID_INFO_PNP_ID = 0x2A50

__all__ = [
    "CONF_ID",
    "CONF_MAC_ADDRESS",
    "CONF_NAME",
    "CONF_PASSWORD",
    "CONF_UPDATE_INTERVAL",
    "DOMAIN",
    "CONF_PAULMANN_LIGHTS_ID",
    "CONF_CONNECTION_RETRIES",
    "CONF_TIMER",
    "CONF_WORKING_MODE",
    "CONF_CONTROLLER_ENABLE",
    "CONF_SYSTEM_ID",
    "CONF_MODEL",
    "CONF_SERIAL_NUMBER",
    "CONF_FIRMWARE_REVISION",
    "CONF_HARDWARE_REVISION",
    "CONF_SOFTWARE_REVISION",
    "CONF_MANUFACTURER",
    "CONF_IEEE_CERTIFICATION",
    "CONF_PNP_ID",
    "DEFAULT_PASSWORD",
    "DEFAULT_NAME",
    "DEFAULT_CONNECTION_RETRIES",
    "DEFAULT_UPDATE_INTERVAL",
]
